### ISSUE TITLE
Panic, when the 'script' section returns an error - invalid option -- XXX

### ISSUE THREAD

**Issue by AlexSol** [umputun/spot#156]
my file spot.xml
```yml
task:
  - name: mkdir
    script: "mkdir -fffff /test_spot"
```
---
trace logs
```
[XX.XX.XX.XX:22] run command "mkdir"
2023/10/10 11:41:14.128 [DEBUG] execute script "mkdir" on XX.XX.XX.XX:22
2023/10/10 11:41:14.128 [DEBUG] command "mkdir" is single line, using script string
2023/10/10 11:41:14.128 [DEBUG] run /bin/sh -c 'mkdir -fffff /test_spot'
2023/10/10 11:41:14.128 [DEBUG] run ssh command "/bin/sh -c 'mkdir -fffff /test_spot'" on XX.XX.XX.XX:22
[XX.XX.XX.XX:22]  > /bin/sh -c 'mkdir -fffff /test_spot'
[XX.XX.XX.XX:22]  ! mkdir: invalid option -- 'f'
[XX.XX.XX.XX:22]  ! Try 'mkdir --help' for more information.
[XX.XX.XX.XX]  ! failed command "mkdir" on host XX.XX.XX.XX:22 (): can't run script on XX.XX.XX.XX:22: failed to run command on remote server: Process exited with status 1
2023/10/10 11:41:14.324 [ERROR] can't run task "default" for target "user@XX.XX.XX.XX:22": 1 error(s) occurred: [0] {failed command "mkdir" on host XX.XX.XX.XX:22 (): can't run script on XX.XX.XX.XX:22: failed to run command on remote server: Process exited with status 1}
>>> stack trace:
main.main()
  /home/alex/Desktop/WOKR_EVA/spot/cmd/spot/main.go:115 +0x272
panic: [ERROR] can't run task "default" for target "user@XX.XX.XX.XX:22": 1 error(s) occurred: [0] {failed command "mkdir" on host XX.XX.XX.XX:22 (): can't run script on XX.XX.XX.XX:22: failed to run command on remote server: Process exited with status 1}

goroutine 1 [running]:
log.Panicf({0xd70bb5?, 0x0?}, {0xc000237f60?, 0xd?, 0x0?})
  /usr/lib/go-1.18/src/log/log.go:392 +0x67
main.main()
  /home/alex/Desktop/WOKR_EVA/spot/cmd/spot/main.go:115 +0x272
```

**Comment by umputun** [comment]
I'm not sure why this is an issue. What behavior would you expect in this case? Spot correctly reported the error and failed. 

Did you mean it may not be the most friendly way to show panic to a user, and this should be shown in verbose or debug mode only?

**Comment by AlexSol** [comment]
I did a couple more tests. You're absolutely right. It's not a bug.

I'm sorry!
